// Writes samples/<type>.md: generated questions per level, for human review against
// the anchors in docs/item-blueprint.md.
//   npm run samples                  -> every generator
//   npm run samples -- number-series -> one generator
import { mkdirSync, writeFileSync } from 'node:fs';
import { generateQuestion } from '../src/engine/question';
import type { DataTable, Generator, Question } from '../src/engine/types';
import { GENERATORS, getGenerator } from '../src/generators/index';

const PER_LEVEL = 4;
const LETTERS = 'ABCDE';

function renderTable(table: DataTable): string {
  const header = `| ${table.rowHeader} | ${table.columns.join(' | ')} |`;
  const rule = `| --- | ${table.columns.map(() => '---:').join(' | ')} |`;
  const rows = table.rows.map((r) => `| ${r.label} | ${r.values.join(' | ')} |`);
  return [`_${table.title} (shown as ${table.display === 'bar' ? 'a bar chart' : 'a table'})_`, '', header, rule, ...rows].join('\n');
}

function render(q: Question): string {
  const choices = q.choices
    .map((c, i) => `${LETTERS[i]}. ${c.text}${i === q.answerIndex ? ' ✅' : ''}`)
    .join('  \n');
  const features = Object.entries(q.features)
    .map(([k, v]) => `${k}=${v}`)
    .join(', ');
  return [
    `**${q.id}**`,
    '',
    ...(q.table ? [renderTable(q.table), ''] : []),
    q.prompt.replace(/\n+/g, '  \n'),
    '',
    choices,
    '',
    `> ${q.explanation}  \n> _features: ${features}_`,
  ].join('\n');
}

function samples(generator: Generator): string {
  const sections = generator.levels.map((level) => {
    const items = Array.from({ length: PER_LEVEL }, (_, i) => generateQuestion(generator, level, 1000 * level + i));
    return `## Level ${level}\n\n${items.map(render).join('\n\n---\n\n')}`;
  });
  return [
    `# Samples: ${generator.label} (\`${generator.type}\`)`,
    '',
    `Generated by \`npm run samples -- ${generator.type}\` with fixed seeds. Compare with the anchors for \`${generator.type}\` in [docs/item-blueprint.md](../docs/item-blueprint.md).`,
    '',
    ...sections.flatMap((s) => [s, '']),
  ].join('\n');
}

const types = process.argv.slice(2);
const selected = types.length ? types.map(getGenerator) : GENERATORS;
mkdirSync('samples', { recursive: true });
for (const generator of selected) {
  writeFileSync(`samples/${generator.type}.md`, samples(generator));
  console.log(`wrote samples/${generator.type}.md`);
}
